import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:quick_jobs/models/user.dart' as app_user;
import 'package:quick_jobs/models/job_post.dart';
import 'package:quick_jobs/models/application.dart';
import 'package:quick_jobs/utils/constants.dart';

class SupabaseService {
  static final SupabaseClient _supabase = Supabase.instance.client;

  // Initialize Supabase
  static Future<void> initialize() async {
    await Supabase.initialize(url: supabaseUrl, anonKey: supabaseAnonKey);
  }

  // Users
  Future<app_user.User?> getUser(String id) async {
    final response = await _supabase
        .from('users')
        .select()
        .eq('id', id)
        .single();

    if (response.isNotEmpty) {
      return app_user.User.fromJson(response);
    }
    return null;
  }

  Future<void> createUser(app_user.User user) async {
    await _supabase.from('users').insert(user.toJson());
  }

  /// Ensure user exists - insert if not, ignore if duplicate
  Future<void> ensureUserExists(app_user.User user) async {
    try {
      await _supabase.from('users').insert(user.toJson());
    } catch (e) {
      if (e.toString().contains('duplicate') ||
          e.toString().contains('23505')) {
        // Unique constraint violation - user already exists, ignore
        print('[SupabaseService] User ${user.id} already exists');
      } else {
        rethrow; // Other errors should be raised
      }
    }
  }

  // Job Posts
  Future<List<JobPost>> getJobPosts({String? professorId}) async {
    var query = _supabase.from('job_posts').select();
    if (professorId != null) {
      query = query.eq('professor_id', professorId);
    }
    final response = await query.order('created_at', ascending: false);
    return response.map((json) => JobPost.fromJson(json)).toList();
  }

  Future<JobPost> createJobPost(JobPost jobPost) async {
    final data = jobPost.toJson()..remove('id'); // Let Supabase generate UUID
    final response = await _supabase
        .from('job_posts')
        .insert(data)
        .select()
        .single();
    return JobPost.fromJson(response);
  }

  Future<void> updateJobPost(String id, Map<String, dynamic> updates) async {
    await _supabase.from('job_posts').update(updates).eq('id', id);
  }

  Future<void> deleteJobPost(String id) async {
    await _supabase.from('job_posts').delete().eq('id', id);
  }

  // Applications
  Future<List<Application>> getApplicationsForJob(String jobPostId) async {
    final response = await _supabase
        .from('applications')
        .select('*, users(*)')
        .eq('job_post_id', jobPostId)
        .order('applied_at', ascending: false);
    return response.map((json) => Application.fromJson(json)).toList();
  }

  Future<List<Application>> getApplicationsForStudent(String studentId) async {
    final response = await _supabase
        .from('applications')
        .select('*, job_posts(*)')
        .eq('student_id', studentId)
        .order('applied_at', ascending: false);
    return response.map((json) => Application.fromJson(json)).toList();
  }

  Future<Application> applyForJob(String studentId, String jobPostId) async {
    final application = Application(
      id: '', // Will be generated by Supabase
      studentId: studentId,
      jobPostId: jobPostId,
      status: 'pending',
      appliedAt: DateTime.now(),
    );

    final response = await _supabase
        .from('applications')
        .insert(application.toJson()..remove('id'))
        .select()
        .single();
    return Application.fromJson(response);
  }

  Future<void> updateApplicationStatus(String id, String status) async {
    await _supabase
        .from('applications')
        .update({
          'status': status,
          'updated_at': DateTime.now().toIso8601String(),
        })
        .eq('id', id);
  }

  // Search
  Future<List<JobPost>> searchJobPosts(String query) async {
    final response = await _supabase
        .from('job_posts')
        .select()
        .or('title.ilike.%$query%,description.ilike.%$query%')
        .eq('status', 'open')
        .order('created_at', ascending: false);
    return response.map((json) => JobPost.fromJson(json)).toList();
  }
}
